config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  resources :users, only: :show
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'ideas#index'
  resources :ideas
  get 'about' => 'static_pages#about'
  get 'random' => 'static_pages#random'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
class Idea < ApplicationRecord
	validates :description, :user_id, presence: true
	
	self.per_page = 10

	belongs_to :user

	delegate :name, to: :user, prefix: true 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :ideas, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])    
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
	before_action :authenticate_user!, only: [:new, :create]
	before_action :is_owner?, only: [:edit, :update, :destroy]
	def index
		@ideas = Idea.order("created_at DESC").paginate(:page => params[:page]).includes(:user)
	end

	def create
	    @idea = current_user.ideas.create(idea_params)
	    if @idea.valid?
	      flash[:success] = "Your idea has been posted!"
	    else
	      flash[:alert] = "Woops! Looks like there has been an error!"
	    end
	    redirect_to root_path
	end

	def edit
		@idea = Idea.find(params[:id])
	end

	def update
	    @idea = Idea.find(params[:id])
	    if @idea.update(idea_params)
	      flash[:success] = "The idea has been updated!"
	      redirect_to root_path
	    else
	      flash[:alert] = "Woops! Looks like there has been an error!"
	      redirect_to edit_idea_path(params[:id])
	    end
	end

	def destroy
	    @idea = Idea.find(params[:id])
	    @idea.destroy
	    flash[:success] = "The idea was successfully deleted!"
	    redirect_to root_path
	end

	private

	def idea_params
	  params.require(:idea).permit(:description, :author, :user_id)
	end

	def is_owner?
	  redirect_to root_path if Idea.find(params[:id]).user != current_user
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def random
  		@idea = Idea.order("RANDOM()").first
  	end

	def about
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ideas/edit.html.erb
<div class="row">
	<div class="col-xs-12 col-md-6 col-md-offset-3">
		<h1>Revise Idea</h1>
		<%= simple_form_for @idea, method: :patch do |f| %>
		<%= f.input :description %>
		  <%= f.input :author %>
		  <%= f.submit 'Submit', class: 'btn btn-success' %>
		<% end %>
	</div>
</div>

app/views/ideas/index.html.erb
<div class="row">
  <div class="col-xs-12 col-md-6 col-md-offset-3">
    <% if user_signed_in? %>
    <button type="button" class="btn btn-success btn-lg btn-block mp-margin" data-toggle="modal" data-target="#myModal">
      <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Add Idea
    </button>


    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
            <h4 class="modal-title" id="myModalLabel">Enter new Idea</h4>
          </div>
          <%= simple_form_for Idea.new do |f| %>
            <div class="modal-body">
              <%= f.input :description %>
              <%= f.input :author, label: 'Remarks' %>
            </div>      
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <%= f.submit 'Submit', class: 'btn btn-success' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <% else %>
      <div class="login-notice">
        <p class="alert alert-info alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>Please <%= link_to 'Log In', new_user_session_path, class: 'alert-link' %> or <%= link_to 'Sign Up', new_user_registration_path, class: 'alert-link' %> to post your Idea.</p>
      </div>
    <% end %>

    <% @ideas.each do |idea| %>
    <div class="panel panel-success">
    	<div class="panel-body">
    	  	<blockquote>
    		  <p><%= idea.description %></p>
    		  <small>By <%= idea.user_name %></small>
    		</blockquote>
    		<br>
        <% if idea.user == current_user %>
    		<%= link_to 'Revise', edit_idea_path(idea), class: 'btn btn-sm btn-success' %>
    		<%= link_to 'Delete', idea_path(idea), method: :delete, class: 'btn btn-sm btn-danger', data: {confirm: "Are you sure?"} %>
        <% end %>
    	</div>
    </div>
    <% end %>

    <div class = "text-center">
      <%= will_paginate @ideas %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ideator</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Dosis|Open+Sans:300,400,600,700" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= favicon_link_tag %>
  </head>

  <body>
  	<div id="wrap">
	  	<%= render 'shared/nav' %>
    <div class = "container">
    	<%= render 'shared/flash_messages' %>
	    <%= yield %>
	 </div>
    </div><!-- wrap -->
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <% if message_type == "notice" %>
    <p class="alert alert-info alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= notice %></p>
  <% elsif message_type == "alert" %>
    <p class="alert alert-danger alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= alert %></p>
  <% else %>
    <div class="alert alert-<%= message_type %> alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= message %></div>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<footer>
	<div class="footer text-center">
		<p>&copy; <a href="http://poudelmadhav.com.np">Madhav Paudel</a> <%= Date.today.year %>. All Rights Reserved.</p>
	</div>
</footer>

app/views/shared/_nav.html.erb
<div class="navbar navbar-default" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="/">Ideator</a>
		</div>
		<div class="navbar-collapse collapse">
			<ul class="nav navbar-nav navbar-right">
				<% if user_signed_in? %>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %><b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li><%= link_to 'My Ideas', user_path(current_user.id) %></li>
							<li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
						    <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
						</ul>
					</li>					
				<% else %>
				    <li><%= link_to 'Sign Up', new_user_registration_path %></li>
				    <li><%= link_to 'Log In', new_user_session_path %></li>
				<% end %>

				<li><%= link_to 'All Ideas', root_path, class: 'active' %></li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">My Websites<b class="caret"></b></a>
					<ul class="dropdown-menu">
						<li class="dropdown-header">Blog</li>
						<li><a href="http://poudelmadhav.me">Blogspot</a></li>
						<li><a href="http://blog.poudelmadhav.com.np">Jekyll</a></li>
						<li class="dropdown-header">Portfolio</li>
						<li><a href="http://poudelmadhav.com.np">Madhav Paudel</a></li>
						<li><a href="http://paudelmadhav.azurewebsites.net">Wordpress</a></li>
					</ul>
				</li>
				<li><%= link_to 'Inspire Me', random_path %></li>
				<li><%= link_to 'About', about_path %></li>
			</ul>
		</div>
	</div>  		
</div>

app/views/static_pages/about.html.erb
<div class="row">
	<div class="col-xs-12 col-md-6 col-md-offset-3">
		<h1>About</h1>

		<h3>Share your ideas with the world and find others.</h3>
	</div>
</div>

app/views/static_pages/random.html.erb
<div class="row">
	<div class="col-xs-12 col-md-6 col-md-offset-3">
		<% if @idea.present? %>
		  <%= link_to 'Inspire Me', random_path, class: 'btn btn-success btn-block' %>
		    
		  <div class="panel panel-success">
		    <div class="panel-body">
		      <blockquote>
		        <p><%= @idea.description %></p>
		        <small>by <%= @idea.user_name %></small>
		      </blockquote>
		       
		      <br>
		      <div class="btn-group" role="group">
		        <% if @idea.user == current_user %>
		    		<%= link_to 'Revise', edit_idea_path(@idea), class: 'btn btn-sm btn-success' %>
		    		<%= link_to 'Delete', idea_path(@idea), method: :delete, class: 'btn btn-sm btn-danger', data: {confirm: "Are you sure?"} %>
		        <% end %>
		      </div>

		    </div>
		  </div>
		  <% else %>
		  <h4>No ideas have been shared. Add one <%= link_to 'here', root_path %></h4>

		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<h3>You have
<%= pluralize(@user.ideas.count, 'post') %> in total: </h3>
</br>
</br>

<% @user.ideas.each do |idea| %>
<div class="panel panel-default">
	<div class="panel-body">
	  	<blockquote>
		  <p><%= idea.description %></p>
		</blockquote>
		<br>
    <% if idea.user == current_user %>
		<%= link_to 'Revise', edit_idea_path(idea), class: 'btn btn-sm btn-success' %>
		<%= link_to 'Delete', idea_path(idea), method: :delete, class: 'btn btn-sm btn-danger', data: {confirm: "Are you sure?"} %>
    <% end %>
	</div>
</div>
<% end %>